Updated by file-sync

diff --git a/.github/workflows/module.yml b/.github/workflows/module.yml
--- a/.github/workflows/module.yml
+++ b/.github/workflows/module.yml
@@ -68,9 +68,30 @@ jobs:
           go mod download
           go test -v -timeout 90m -run ${{ matrix.testcase }}
 
+  check-tests:
+    needs: run-test
+    runs-on: ubuntu-latest
+    if: success()
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
+    steps:
+      - id: setoutput
+        working-directory: .
+        run: echo "::set-output name=success::true"
+
   module:
     runs-on: ubuntu-latest
-    needs: run-test
+    if: always()
+    needs: [run-test, check-tests]
     steps:
-    - run: echo Done!
-      working-directory: .
+      - name: module
+        working-directory: .
+        run: |
+          passed="${{ needs.check-tests.outputs.success }}"
+          if [[ $passed == "true" ]]; then
+            echo "tests passed"
+            exit 0
+          else
+            echo "tests failed"
+            exit 1
+          fi
